version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/mcesar-d/data/mariadb
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/mcesar-d/data/wordpress

networks:
  inception:
    external: true